version: "2"

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"

  jobs:
    pre_build:
      - pip install .
      - pip install sphinx-pdj-theme
sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
