version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.13"

  jobs:
    pre_build:
      - pip install mkdocs-material mkdocs-awesome-nav
mkdocs:
  configuration: mkdocs.yml

formats:
  - pdf
  - epub
